import {useEffect,useMemo,useState} from "react";
import "./App.css";
const API="http://localhost:3001",SIZES=["36","37","38","39","40","41"],n=v=>Number(v||0);
const money=v=>n(v).toLocaleString("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0});
const iu=p=>!p?"":p.startsWith("/uploads/")?API+p:p;
const stock=p=>(p.colors||[]).reduce((s,c)=>s+Object.values(c.sizes||{}).reduce((a,v)=>a+n(v),0),0);
const price=p=>p.salePrice!=null?n(p.salePrice):Math.round(n(p.price)*(1-Math.min(100,Math.max(0,n(p.discount)))/100)*100)/100;
const first=p=>p.colors?.[0]?.images?.[0]||p.colors?.[0]?.image||p.image||"";

export default function App(){
 const [products,setProducts]=useState([]),[settings,setSettings]=useState({}),[page,setPage]=useState("home"),[filter,setFilter]=useState("Tümü"),[search,setSearch]=useState("");
 const [selected,setSelected]=useState(null),[color,setColor]=useState(null),[size,setSize]=useState(null),[photo,setPhoto]=useState(""),[reviews,setReviews]=useState([]);
 const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("sheliva-cart")||"[]")),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false);
 const [token,setToken]=useState(()=>localStorage.getItem("sheliva-token")||""),[user,setUser]=useState(null),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState("login"),[otpSent,setOtpSent]=useState(false),[myOrders,setMyOrders]=useState([]);

 async function refresh(){try{const [p,s]=await Promise.all([fetch(`${API}/api/products`),fetch(`${API}/api/settings`)]);setProducts((await p.json()).filter(x=>x.active!==false));setSettings(await s.json())}catch{}}
 async function me(t=token){if(!t)return;const r=await fetch(`${API}/api/auth/me`,{headers:{Authorization:`Bearer ${t}`}});if(r.ok)setUser(await r.json())}
 useEffect(()=>{refresh();me();const t=setInterval(refresh,2500);return()=>clearInterval(t)},[]);
 useEffect(()=>localStorage.setItem("sheliva-cart",JSON.stringify(cart)),[cart]);

 const shown=useMemo(()=>{let x=[...products];if(filter!=="Tümü"&&["Yazlık","Kışlık"].includes(filter))x=x.filter(p=>p.category===filter);if(filter==="İndirimde")x=x.filter(p=>n(p.discount)>0);if(filter==="Yeni Sezon")x=x.filter(p=>p.newest!==false);if(filter==="Son Gelenler")x.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(search)x=x.filter(p=>p.name.toLocaleLowerCase("tr").includes(search.toLocaleLowerCase("tr")));return x},[products,filter,search]);
 const count=cart.reduce((s,i)=>s+n(i.qty),0),sub=cart.reduce((s,i)=>s+n(i.qty)*n(i.price),0),cargo=sub>=n(settings.freeShippingThreshold)?0:n(settings.cargoFee),total=sub+cargo;
 const promo=products.filter(p=>n(p.discount)>0&&stock(p)>0)[0]||[...products].sort((a,b)=>n(b.totalSold)-n(a.totalSold))[0];

 async function openProduct(p){const c=p.colors?.[0]||null;setSelected(p);setColor(c);setSize(null);setPhoto(c?.images?.[0]||c?.image||p.image||"");setPage("product");window.scrollTo(0,0);const r=await fetch(`${API}/api/products/${p.id}/reviews`);if(r.ok)setReviews(await r.json())}
 function add(){if(!color||!size)return;const st=n(color.sizes?.[size]);if(st<=0)return;const key=`${selected.id}-${color.id}-${size}`;setCart(prev=>{const f=prev.find(x=>x.key===key);if(f){if(f.qty>=st)return prev;return prev.map(x=>x.key===key?{...x,qty:x.qty+1,maxStock:st}:x)}return[...prev,{key,productId:selected.id,name:selected.name,colorId:color.id,colorName:color.name,size,image:color.images?.[0]||color.image||selected.image,price:price(selected),qty:1,maxStock:st}]});setCartOpen(true)}
 function qty(k,d){setCart(prev=>prev.map(i=>{if(i.key!==k)return i;const p=products.find(x=>n(x.id)===n(i.productId)),c=p?.colors?.find(x=>x.id===i.colorId),st=n(c?.sizes?.[i.size]),q=i.qty+d;if(d>0&&q>st)return i;return{...i,qty:q,maxStock:st}}).filter(i=>i.qty>0))}
 async function reqOtp(e){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch(`${API}/api/auth/request-otp`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:f.get("phone")})});if(!r.ok)return alert((await r.json()).error);setOtpSent(true);alert("Kod 3001 PowerShell ekranında.")}
 async function register(e){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch(`${API}/api/auth/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f.entries()))}),d=await r.json();if(!r.ok)return alert(d.error);localStorage.setItem("sheliva-token",d.token);setToken(d.token);setUser(d.user);setAuthOpen(false)}
 async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch(`${API}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f.entries()))}),d=await r.json();if(!r.ok)return alert(d.error);localStorage.setItem("sheliva-token",d.token);setToken(d.token);setUser(d.user);setAuthOpen(false)}
 async function loadOrders(){if(!token)return;const r=await fetch(`${API}/api/account/orders`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok)setMyOrders(await r.json())}
 async function placeOrder(e){e.preventDefault();if(!user)return setAuthOpen(true);const f=new FormData(e.currentTarget),r=await fetch(`${API}/api/orders`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({customer:{name:f.get("name"),phone:f.get("phone"),email:f.get("email"),city:f.get("city"),district:f.get("district"),neighborhood:f.get("neighborhood"),postalCode:f.get("postalCode"),address:f.get("address"),note:f.get("note")},paymentMethod:f.get("paymentMethod"),items:cart})}),d=await r.json();if(!r.ok)return alert(d.error);alert(`Sipariş alındı: ${d.orderNo}`);setCart([]);setCheckout(false);setCartOpen(false);refresh()}
 async function account(){if(!user)return setAuthOpen(true);await loadOrders();setPage("account");setCartOpen(false)}
 async function review(e){e.preventDefault();if(!user)return setAuthOpen(true);const f=new FormData(e.currentTarget);const r=await fetch(`${API}/api/reviews`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({productId:selected.id,rating:n(f.get("rating")),text:f.get("text")})});if(r.ok){e.currentTarget.reset();alert("Yorum onaya gönderildi.")}}
 async function ret(id){const reason=prompt("İade sebebi");if(!reason)return;const r=await fetch(`${API}/api/returns`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({orderId:id,reason})});if(!r.ok)alert((await r.json()).error);else alert("İade talebi açıldı.")}

 return <div>
  <header className="top"><button onClick={()=>setPage("home")}>☰ MENU</button><button className="brand" onClick={()=>setPage("home")}>SHELİVA</button><div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ara"/><button onClick={account}>{user?"HESABIM":"GİRİŞ"}</button><button onClick={()=>setCartOpen(true)}>SEPET <b>{count}</b></button></div></header>
  {page==="home"&&<main className="home">
   <section className="hero">{promo&&<img src={iu(first(promo))}/>}<div><small>SHELİVA</small><h1>{promo&&n(promo.discount)>0?"İndirimde Öne Çıkan":"Yeni Koleksiyon"}</h1><p>{promo?.name}</p>{promo&&<button onClick={()=>openProduct(promo)}>İNCELE</button>}</div></section>
   <section className="cats">{["Yazlık","Kışlık","Yeni Sezon","İndirimde","Tümü","Son Gelenler"].map(x=><button key={x} onClick={()=>setFilter(x)}>{x}</button>)}</section>
   <section className="products"><h2>{filter==="Tümü"?"Tüm Ürünler":filter}</h2><div className="productGrid">{shown.map(p=><article key={p.id} onClick={()=>openProduct(p)}><div className="pimg">{first(p)&&<img src={iu(first(p))}/>} {n(p.discount)>0&&<em>%{p.discount}</em>}</div><div className="pbody"><small>{p.category}</small><h3>{p.name}</h3><div>{n(p.discount)>0&&<del>{money(p.price)}</del>}<strong>{money(price(p))}</strong></div><span>{stock(p)>0?`${stock(p)} stok`:"Tükendi"}</span><button disabled={stock(p)<=0}>İNCELE</button></div></article>)}</div></section>
  </main>}

  {page==="product"&&selected&&<main className="detail"><button onClick={()=>setPage("home")}>← Ana Sayfa</button><section><div className="gallery"><aside>{(color?.images||[]).map((x,i)=><button key={i} onClick={()=>setPhoto(x)}><img src={iu(x)}/></button>)}</aside><div>{photo&&<img src={iu(photo)}/>}</div></div><div className="productInfo"><small>{selected.code}</small><h1>{selected.name}</h1><p>{selected.description}</p><div className="price">{n(selected.discount)>0&&<del>{money(selected.price)}</del>}<strong>{money(price(selected))}</strong></div><label>RENK</label><div className="colors">{(selected.colors||[]).map(c=><button key={c.id} className={color?.id===c.id?"active":""} onClick={()=>{setColor(c);setSize(null);setPhoto(c.images?.[0]||"")}}>{c.images?.[0]&&<img src={iu(c.images[0])}/>}<span>{c.name}</span></button>)}</div><label>NUMARA</label><div className="sizes">{SIZES.map(s=><button key={s} disabled={n(color?.sizes?.[s])<=0} className={size===s?"active":""} onClick={()=>setSize(s)}>{s}<small>{n(color?.sizes?.[s])||"Yok"}</small></button>)}</div><button className="add" disabled={!size||n(color?.sizes?.[size])<=0} onClick={add}>{size?"SEPETE EKLE":"NUMARA SEÇ"}</button><div className="trust"><span>Güvenli alışveriş</span><span>Gerçek stok</span><span>Sipariş takibi</span></div><div className="reviews"><h3>Yorumlar</h3>{reviews.map(r=><article key={r.id}><b>{r.userName} • {"★".repeat(r.rating)}</b><p>{r.text}</p></article>)}<form onSubmit={review}><select name="rating"><option value="5">5 Yıldız</option><option value="4">4 Yıldız</option><option value="3">3 Yıldız</option></select><textarea name="text" required placeholder="Yorum"/><button>GÖNDER</button></form></div></div></section></main>}

  {page==="account"&&user&&<main className="account"><div className="accountHead"><div><small>HESABIM</small><h1>{user.name}</h1><p>{user.phone} • {user.email}</p></div></div><h2>Siparişlerim</h2>{myOrders.map(o=><article key={o.id}><div><b>{o.orderNo}</b><h3>{o.status}</h3><p>{new Date(o.createdAt).toLocaleString("tr-TR")}</p></div><div><strong>{money(o.total)}</strong>{o.status==="Kargoya Verildi"&&<span>{o.cargoCompany} • {o.cargoTracking}</span>}{o.status==="Teslim Edildi"&&<button onClick={()=>ret(o.id)}>İADE TALEBİ</button>}</div></article>)}</main>}

  <footer className="footer"><div><h2>SHELİVA</h2><p>Modern ayakkabı koleksiyonları.</p></div><div><b>ALIŞVERİŞ</b><span>Yazlık</span><span>Kışlık</span><span>İndirimde</span></div><div><b>DESTEK</b><span>Sipariş Takibi</span><span>İade & Değişim</span><span>{settings.supportPhone||"Destek hattı"}</span></div><div><b>HESAP</b><span>Giriş / Kayıt</span><span>Siparişlerim</span></div><small>© 2026 SHELİVA</small></footer>

  <div className={cartOpen?"shade show":"shade"} onClick={()=>setCartOpen(false)}></div>
  <aside className={cartOpen?"drawer open":"drawer"}><header><div><small>SHELİVA</small><h2>Sepetim ({count})</h2></div><button onClick={()=>setCartOpen(false)}>×</button></header>{!checkout?<><div className="cartItems">{cart.map(i=><article key={i.key}><img src={iu(i.image)}/><div><h3>{i.name}</h3><p>{i.colorName} • {i.size}</p><strong>{money(i.price*i.qty)}</strong><div className="qty"><button onClick={()=>qty(i.key,-1)}>−</button><span>{i.qty}</span><button disabled={i.qty>=i.maxStock} onClick={()=>qty(i.key,1)}>+</button></div><small>Maksimum {i.maxStock} adet</small></div><button className="remove" onClick={()=>setCart(cart.filter(x=>x.key!==i.key))}>×</button></article>)}</div>{!!cart.length&&<footer><p><span>Ara Toplam</span><b>{money(sub)}</b></p><p><span>Kargo</span><b>{cargo?money(cargo):"Ücretsiz"}</b></p><p className="grand"><span>Toplam</span><strong>{money(total)}</strong></p><button onClick={()=>user?setCheckout(true):setAuthOpen(true)}>{user?"GÜVENLİ ÖDEMEYE GEÇ":"GİRİŞ YAP VE DEVAM ET"}</button></footer>}</>:<form className="checkout" onSubmit={placeOrder}><button type="button" onClick={()=>setCheckout(false)}>← Sepete dön</button><h2>Teslimat Bilgileri</h2><div className="two"><input name="name" defaultValue={user.name} required placeholder="Ad Soyad"/><input name="phone" defaultValue={user.phone} required placeholder="Telefon"/></div><input name="email" defaultValue={user.email} required/><div className="two"><input name="city" required placeholder="İl"/><input name="district" required placeholder="İlçe"/></div><div className="two"><input name="neighborhood" placeholder="Mahalle"/><input name="postalCode" placeholder="Posta kodu"/></div><textarea name="address" required placeholder="Açık adres"/><textarea name="note" placeholder="Sipariş notu"/><select name="paymentMethod"><option>Kapıda / Taslak</option><option>Havale / EFT</option><option>Kart (entegrasyon sonrası)</option></select><div className="checkoutTotal"><span>Toplam</span><strong>{money(total)}</strong></div><button className="place">SİPARİŞİ ONAYLA</button></form>}</aside>

  {authOpen&&<div className="auth"><div><header><h2>{authMode==="login"?"Giriş Yap":"Kayıt Ol"}</h2><button onClick={()=>setAuthOpen(false)}>×</button></header><nav><button className={authMode==="login"?"active":""} onClick={()=>{setAuthMode("login");setOtpSent(false)}}>GİRİŞ</button><button className={authMode==="register"?"active":""} onClick={()=>{setAuthMode("register");setOtpSent(false)}}>KAYIT OL</button></nav>{authMode==="login"?<form onSubmit={login}><input name="login" required placeholder="Telefon veya e-posta"/><input name="password" type="password" required placeholder="Şifre"/><button>GİRİŞ YAP</button></form>:!otpSent?<form onSubmit={reqOtp}><input name="phone" required placeholder="05xx xxx xx xx"/><p>Test kodu 3001 PowerShell ekranına gelir.</p><button>KOD GÖNDER</button></form>:<form onSubmit={register}><input name="name" required placeholder="Ad Soyad"/><input name="phone" required placeholder="Telefon"/><input name="email" type="email" required placeholder="E-posta"/><input name="password" type="password" required placeholder="Şifre"/><input name="code" required placeholder="6 haneli kod"/><button>HESABI OLUŞTUR</button></form>}</div></div>}
 </div>
}
